version: '2'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    command: --smallfiles --rest --auth
  server:
    build: .
    ports:
     - "8000:8000"
    volumes:
     - .:/code
