version: '2'
services:
  mongodata:
    image: mongo
    volumes:
      - /data/db
    command: --break-mongo
  mongo:
    image: mongo
    volumes_from:
      - mongodata
    ports:
      - "27017:27017"
    command: --smallfiles --rest --auth
  server:
    build: .
    ports:
     - "8000:8000"
    volumes:
     - .:/code
